blank_issues_enabled: false
contact_links:
  - name: Questions, Discussions
    url: https://github.com/AvaloniaUI/avalonia-dotnet-templates/discussions/new
    about: Please ask and answer questions here.
  - name: Avalonia Community Support on Telegram
    url: https://t.me/Avalonia
    about: Please ask and answer questions here.
